### PR TITLE
(#869) Ensure bundle update on convert/update

### LINKED ISSUE #869: GemNotFound error for public_suffix-3.1.1 when using --add-tests
**Describe the bug**
In a clean PDK install, which has not run `pdk test unit` yet, I tried to add spec test to an existing module. I ran `pdk convert --add-tests` but got an error message:

```
[✖] Examining module contents
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/util/puppet_strings.rb:42:in `generate_hash': /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize': Could not find public_suffix-3.1.1 in any of the sources (Bundler::GemNotFound) (PDK::Util::PuppetStrings::RunError)
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kevin.reeuwijk/code/vmtools_win/bin/puppet:15:in `<main>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/util/puppet_strings.rb:98:in `all_objects'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:98:in `test_generators'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:91:in `missing_tests?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:87:in `adding_tests?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:69:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:7:in `invoke'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/cli/convert.rb:51:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/cli.rb:68:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/bin/pdk:23:in `<main>'
```

This error didn't show up later anymore, after `pdk test unit` had run.

**Additional context**
- PDK installation method: homebrew
- PDK version: 1.17.0
- Operating system / platform: MacOS Catalina

### PR DESCRIPTION
**Pull request by rodjek**
Change the upgrade & convert process so that it always ensures the bundle is up to date. Depending on detecting changes to `Gemfile` is not sufficient as it doesn't detect changes to unlisted dependencies.

Fixes #869

### CODE REVIEW

File: lib/pdk/module/update.rb [hunk 1]
```diff
@@ -33,19 +33,15 @@ def run
...
 
         update_manager.sync_changes!
 
-        if needs_bundle_update?
-          require 'pdk/util/bundler'
-
-          PDK::Util::Bundler.ensure_bundle!
-        end
+        require 'pdk/util/bundler'
+        PDK::Util::Bundler.ensure_bundle!
```
Comment (glennsarti) [inline lib/pdk/module/update.rb]: Should this be a user prompt?

`Would you like to update your bundle?`

**Comment by glennsarti** [comment]
Could probably copy the PR comment into the commit message too.

File: lib/pdk/module/update.rb (hunk 1 above)
Comment (rodjek) [reply lib/pdk/module/update.rb]: No, I don't think so. If it doesn't update, then it'll just happen automatically when they run the next PDK command.

Comment (glennsarti) [reply lib/pdk/module/update.rb]: Only usecase I can think of is bundle taking FOREVER (looking at you Windows) and wanting to stop that for tools like `pdksync`.  But I'm more than happy to add that later if needs be.
