### PR TITLE
(GH-874) Use PDK Context root for PDK Convert and Update

### LINKED ISSUE #874: 'pdk convert' of a module that's inside a control repo adds boilerplate to the control repo
**Describe the bug**
Running `pdk convert` from an existing non-PDK module in a control-repo causes all of the new module boilerplate to be created at the root of the control-repo, not in the module.

**To Reproduce**
Given:
* `~/src/control-repo` is a control repository with an `environment.conf` and `metadata.json` file
* `~/src/control-repo/site/foo` is an existing, non-PDK module
* `~/src/control-repo/site/foo` is an existing module that does **not** contain a `metadata.json`

Run:
```
[~/src/control-repo/site/foo]$ pdk convert
```

**Actual behavior**

All of the boilerplate gets created at the root of the control-repo.
```
[~/src/control-repo]$ cd site/foo
[~/src/control-repo/site/foo]$ pdk convert
------------Files to be added-----------
/Users/nate/src/control-repo/.pdkignore
/Users/nate/src/control-repo/.yardopts
/Users/nate/src/control-repo/spec/spec_helper.rb
/Users/nate/src/control-repo/spec/default_facts.yml
/Users/nate/src/control-repo/.rubocop.yml
/Users/nate/src/control-repo/.rspec
/Users/nate/src/control-repo/.gitattributes
/Users/nate/src/control-repo/Rakefile
/Users/nate/src/control-repo/.vscode/extensions.json
/Users/nate/src/control-repo/.fixtures.yml
/Users/nate/src/control-repo/CHANGELOG.md
----------Files to be modified----------
/Users/nate/src/control-repo/metadata.json
/Users/nate/src/control-repo/Gemfile
/Users/nate/src/control-repo/.gitignore
/Users/nate/src/control-repo/.puppet-lint.rc
----------------------------------------
You can find a report of differences in convert_report.txt.
```

**Expected behavior**
I expect all of the boilerplate to be created in the directory in which I ran `pdk convert`, which is `~/src/control-repo/site/foo`

**Additional context**
- PDK 1.17.0
- MacOS 10.15.3
- Installed with Homebrew

### PR DESCRIPTION
**Pull request by glennsarti**
Fixes #874 

Blocking until #872 is merged due to possible merge conflicts

Previously the pdk update and convert CLI commands had a strange failure mode
where if a "module" was nested inside another "module" but only the parent had
a metadata.json. When a user tried to update or convert the child module, the
files would be put in the parent.  This was due to the CLI using the lax
detection (in_module_root?) method to "find" the module, but use the strict
detection method (module_root) during the actual conversion.

This commit updates these CLI logic to use the new PDK.context object which
is far more consistent.  This commit also adds a test for these scenarios in
PDK update and convert.

### CODE REVIEW

File: lib/pdk/cli/convert.rb [hunk 1]
```diff
@@ -14,14 +14,15 @@ module PDK::CLI
...
-        message:             _('`pdk convert` can only be run from inside a valid module directory.'),
-        log_level:           :info,
-      )
+      # Write the context information to the debug log
+      PDK.context.to_debug_log
+
+      unless PDK.context.is_a?(PDK::Context::Module)
+        raise PDK::CLI::ExitWithError.new(
+          _('`pdk convert` can only be run from inside a valid module directory.'),
+          log_level: :error,
```
Comment (rodjek) [inline lib/pdk/cli/convert.rb]: nit: `PDK::CLI::ExitWithError` defaults to the `:error` log level

File: lib/pdk/cli/update.rb [hunk 2]
```diff
@@ -10,14 +10,15 @@ module PDK::CLI
...
+      PDK.context.to_debug_log
 
-      PDK::CLI::Util.ensure_in_module!(
-        message:   _('`pdk update` can only be run from inside a valid module directory.'),
-        log_level: :info,
-      )
+      unless PDK.context.is_a?(PDK::Context::Module)
+        raise PDK::CLI::ExitWithError.new(
+          _('`pdk update` can only be run from inside a valid module directory.'),
+          log_level: :error,
```
Comment (rodjek) [inline lib/pdk/cli/update.rb]: nit: `PDK::CLI::ExitWithError` defaults to the `:error` log level

File: lib/pdk/cli/convert.rb (hunk 1 above)
Comment (glennsarti) [reply lib/pdk/cli/convert.rb]: Fixed

File: lib/pdk/cli/update.rb (hunk 2 above)
Comment (glennsarti) [reply lib/pdk/cli/update.rb]: Fixed
